language: python

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/
    - /^hotfix\/.*$/

python:
  - 2.7

install:
  - pip install -r requirements.txt

script:
  - python -m tests.conf
